# Generated by Django 5.0.6 on 2024-06-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="user",
        ),
        migrations.RemoveField(
            model_name="hrmanager",
            name="user",
        ),
        migrations.AddField(
            model_name="employee",
            name="email",
            field=models.EmailField(default="", max_length=254),
        ),
        migrations.AddField(
            model_name="employee",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="hrmanager",
            name="email",
            field=models.EmailField(default="", max_length=254),
        ),
        migrations.AddField(
            model_name="hrmanager",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="itsupport",
            name="status",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="onboardingtask",
            name="status",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="trainingmodule",
            name="status",
            field=models.CharField(max_length=50),
        ),
    ]
