# Generated by Django 5.0.6 on 2024-06-24 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_employee_user_remove_hrmanager_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="email",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="name",
        ),
        migrations.RemoveField(
            model_name="hrmanager",
            name="email",
        ),
        migrations.RemoveField(
            model_name="hrmanager",
            name="name",
        ),
        migrations.AddField(
            model_name="employee",
            name="user",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="hrmanager",
            name="user",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="employee",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="core.employee",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(default="Pending", max_length=50),
        ),
        migrations.AlterField(
            model_name="itsupport",
            name="employee",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="it_support",
                to="core.employee",
            ),
        ),
        migrations.AlterField(
            model_name="itsupport",
            name="status",
            field=models.CharField(default="Pending", max_length=50),
        ),
        migrations.AlterField(
            model_name="onboardingtask",
            name="employee",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="core.employee",
            ),
        ),
        migrations.AlterField(
            model_name="onboardingtask",
            name="status",
            field=models.CharField(default="Pending", max_length=50),
        ),
        migrations.AlterField(
            model_name="trainingmodule",
            name="employee",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="training_modules",
                to="core.employee",
            ),
        ),
        migrations.AlterField(
            model_name="trainingmodule",
            name="status",
            field=models.CharField(default="Pending", max_length=50),
        ),
    ]
