# Generated by Django 5.0.7 on 2024-07-26 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_student_options_alter_student_managers_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supervisor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Advice",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("advice", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.student"
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.supervisor"
                    ),
                ),
            ],
        ),
    ]
